const ADD_TILES = 'ADD_TILES';
const FLIP_TILE = 'FLIP_TILE';
const RESET_TILES = 'RESET_TILES';
const HANDLE_MATCH = 'HANDLE_MATCH';
const ADVANCE_TURN = 'ADVANCE_TURN';

const types = {
  ADD_TILES,
  FLIP_TILE,
  RESET_TILES,
  HANDLE_MATCH,
  ADVANCE_TURN,
};

export default types;
