const ADD_TILES = 'ADD_TILES';
const FLIP_TILE = 'FLIP_TILE';
const HANDLE_FLIPPED_PAIR = 'HANDLE_FLIPPED_PAIR';
const HANDLE_GAME_OVER = 'HANDLE_GAME_OVER';

const types = {
  ADD_TILES,
  FLIP_TILE,
  HANDLE_FLIPPED_PAIR,
  HANDLE_GAME_OVER,
};

export default types;
