const UPDATE_NAMES = 'UPDATE_NAMES';
const UPDATE_STAGE = 'UPDATE_STAGE';
const ADD_TILES = 'ADD_TILES';
const FLIP_TILE = 'FLIP_TILE';
const HANDLE_FLIPPED_PAIR = 'HANDLE_FLIPPED_PAIR';
const HANDLE_GAME_OVER = 'HANDLE_GAME_OVER';
const RESET_GAME = 'RESET_GAME';

const types = {
  UPDATE_NAMES,
  UPDATE_STAGE,
  ADD_TILES,
  FLIP_TILE,
  HANDLE_FLIPPED_PAIR,
  HANDLE_GAME_OVER,
  RESET_GAME,
};

export default types;
