name: 'Deploy to Oracle'
on:
  push:
    branches:
      - 'replace-nx-with-turborepo'

jobs:
  install_oracle_cli:
    runs-on: ubuntu-latest
    steps:
      name: 'Install Oracle CLI'
      run: |
        curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
        chmod +x install.sh
        ./install.sh --accept-all-defaults
        echo "::add-path::/home/runner/bin"
        exec -l $SHELL

